= Schicksalhafte Schatten: Ein _Fate Core_ Rollenspiel im _Shadowrun_-Universum
:author: Alexander Metzner <alexander.metzner@gmail.com>
:revnumber: 0.2.0
:revnumber-caption: Version
:doctype: book
:note-caption: Hinweis
:caution-caption: Work in progress
:toc:
:toc-title: Inhaltsverzeichnis
:toclevels: 4
:example-caption: Beispiel
:sectanchors:
:sectnums:
:chapter-signifier: Kapitel

[preface]
== Einleitung
_Schicksalhafte Schatten_ ist eine Adaption des generischen Regelsystems von _Fate Core_ an die Welt von 
https://www.shadowrun6.de/[_Shadowrun_ in der 6. Edition]. Diese Regeln basieren auf den Regeln aus dem 
https://faterpg.de/download/offiziellesmaterial/fate_core,_turbo-fate,_fate_accelerated/Fate-Core_Downloadversion.pdf[Fate Core Grundregelwerk Version 2.0].

Diese Adaption verfolgt das Ziel, ein möglichst einfaches System von Regeln zur Verfügung zu stellen,
um spannende und unterhaltsame Geschichten in der Welt von Shadowrun gemeinsam zu erzählen, ohne dabei 
auf unzählige Regeln, Bücher, Tabellen und weiteres angewiesen zu sein. Dabei werden die Aspekte, die eine
zentrale Rolle im Fate Core System spielen intensiv genutzt. 

Diese Regeln verzichten auf große Kataloge von Waffen, Rüstungen, Ausrüstung, Zauber, Programme und Fahrzeuge.
Statt dessen werden Aspekte genutzt, um individuelle Ausprägungen zu repräsentieren. Dies soll den Spielfluss
verbessern und den Fokus auf die Erzählung legen.

CAUTION: Diese Regeln sind zur Zeit noch in der Entwicklung und werden in Teilen überarbeitet.

== Konzept, Dilemma und Charakteraspekte

Bei der Erschaffung eines Charakters für _Fate Core_ legt der Spieler zunächst *Konzept* und *Dilemma* des
Charakters fest. Dies gilt auch für _Schicksalhafte Schatten_. Danach kannst Du noch drei weitere Aspekte
wählen.

=== Konzept

Das *Konzept* beschreibt den zentralen Grundgedanken des Charakters als kompakte Phrase. Für _Schicksalhafte
Schatten_ sind hier zwei Bestandteile wesentlich: der Metatypus des Charakters sowie "erwachte" Fähigkeiten 
wie Magie oder Resonanz. Diese müssen sich im Konzept wiederfinden wenn der Charakter über entsprechende
Eigenschaften verfügen soll.

==== Metatypen

Shadowrun kennt _Metatypen_ für die Runner. Dazu zählen Menschen, Elfen, Zwerge, Orks und Trolle. Die
Metatypen werden in _Schicksalhafte Schatten_ durch das *Konzept* des Charakters repräsentiert und können im
Verlauf des Spiels _nicht mehr geändert_ werden.

Du kannst den Metatypus-Teil des Konzepts als Aspekt nutzen, wenn Dein Metatypus Dir entsprechende 
Vorteile bietet (bspw. Dunkelsicht für Elfen als +2 Bonus auf Wahrnehmung). Dies gilt als Einsatz des 
Aspekts und kostet wie üblich einen Fate Punkt.

Die besondere Trollhaut, die Dir eine zusätzliche Panzerung bringt, wird als Stunt umgesetzt, der gegen Dein 
Limit von Stunts zählt. Dieser Stunt erlaubt Dir, die Rüstungsstufe um 1 zu erhöhen (siehe 
<<Waffen und Rüstungen>>).

==== Nutzung von Magie

In der Welt von Shadowrun existieren verschiedene Formen von Magie verwendenden Archetypen: Magier, 
Hexenmeister, Schamane oder Adpeten. Für _Schicksalhafte Schatten_ wird die Art der Magie regeltechnisch
identisch behandelt - in Form der Fertigkeit _Magie_. Die Art, wie die Magie gewirkt wird, sollte sich
aber in der Art der Erzählung unterscheiden.

Damit ein Charakter Zugriff auf die Fertigkeit _Magie_ hat, muss der entsprechende Archetypus im 
_Konzept_ erwähnt werden.

==== Technomancer

In der Welt von Shadowrun existieren _Techomancer_, die durch Nutzung der sogenannten Resonanz die 
Matrix ohne Verwendung von Cyberdecks oder anderem technischen Gerät nutzen können. Damit ein Charakter
diese Fähigkeiten nutzen kann, muss er im Konzept den Archetypus _Technomancer_ erwähnen. Die genauen
Regeln sind unter <<Matrix>> beschrieben.

==== Beispiele

====
* zwergischer Ex-Kon Rigger
* aggressiver elfischer Kampfmagier
* technologiefeindlicher Ork-Sumpf-Schamane
* neurotischer Troll-Technomancer
====

=== Dilemma

Hier gilt alles, was auch in den Fate Core Grundregeln zum Dilemma gesagt wird. Im Shadowrun-Universum gibt
es im Besonderen ein Potential für ein Dilemma, das andere Personen oder Organisationen betrifft. Ein Runner,
der zuvor als Konzern-Decker gearbeitet hat, könnte eine besondere "Hass-Liebe" zu seinem ehemaligen 
Arbeitgeber pflegen. Ein Magier, der früh im Rahmen einer "Talentförderung" von einem Konzern bedrängt wurde,
hat ebenso ein besonders ablehnendes Verhältnis zu Konzernen im Allgemeinen. Der Straßensamurai könnte in 
seiner Jungend viel mit einer Gang im Streit gelegen haben oder Unterdrückung durch eine kriminelle 
Organisation erfahren haben. 

Diese Arten von Dilemmas bieten viel Potential für spannende Komplikationen, Konflikte oder auch ein kleines
"Intermezzo". Natürlich kannst Du auch eine andere Art von Dilemma wählen. Eine Drogensucht oder auch eine
Abhängigkeit von heißem Sim bieten ebenfalls das Potential für Komplikationen in der Geschichte und damit: 
Drama!

Beispiele für Dilemma:

====
* Die Razor-Gang jagd mich
* Don Frederic hat ein Kopfgeld auf meinen Kopf ausgesetzt
====

=== Aspekte



== Fertigkeiten

_Schicksalhafte Schatten_ nutzt die vollständige Liste der Fertigkeiten aus _Fate Core_. Einige der Fertigkeiten
werden modifiziert oder eingeschränkt. Es kommen einige (wenige) neue Fertigkeiten hinzu.

=== Übersicht

Die folgende Tabelle gibt einen Überblick über alle Fertigkeiten und welche Aktionen mit der jeweiligen
Fertigkeit möglich sind.

<<<

[frame=ends, grid=rows, stripes=even, cols="<2h,4*^1"]
|===
| Fertigkeit | [.icon]#O# | [.icon]#C# | [.icon]#A# | [.icon]#D#

| Athletik        | X | X |   | X 
| Charisma        | X | X |   | X
| Diebeskunst     | X | X |   |   
| Empathie        | X | X |   | X 
| Fahren          | X | X | X | X 
| Handwerk / Tech | X | X |   |   
| Hacken *        | X | X |   | 
| Heimlichkeit    | X | X |   | X
| Kämpfen         | X | X | X | X 
| Kontakte        | X | X |   | X
| Kraft           | X | X |   | X 
| Magie  *        | X | X | X | X 
| Matrixkampf  *  | X | X | X | X 
| Nachforschungen | X | X |   |   
| Provozieren     | X | X | X |
| Ressourcen *    | X | X | X | X
| Schießen        | X | X | X |   
| Täuschung       | X | X |   | X
| Wahrnehmung     | X | X |   | X 
| Wille           | X | X |   | X
| Wissen          | X | X |   | X 
|===

NOTE: Fertigkeiten, hinter deren Namen ein Sternchen steht, können nur eingeschränkt erworben/
gesteigert werden. Schau in die Beschreibung dieser Fertigkeiten.

=== Beschreibung der Fertigkeiten

==== Athletik

Athletik wird so eingesetzt wie in den _Fate Core Grundregeln_ beschrieben. Diese Fertigkeit dient der 
Bewegung in der realen Welt. Bewegungungen in der Astalebene oder der Matrix nutzen andere Fertigkeiten. 

[.icon]#D# Du kannst _Athletik_ zur Verteidigung gegen alle Arten von Angriffen einsetzen (Nahkampf-
wie Fernkampfangriffe).

==== Charisma

Charisma wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.

==== Diebeskunst

Mit Diebeskunst kannst Du Gegenstände stehlen oder Spuren in der realen Welt verwischen. Du kannst Dich auch
an Orte bewegen, an denen Du nicht sein solltest, vorausgesetzt, es gibt keine technologisch weit entwickelten
Sicherungsmaßnahmen (dann würdest Du <<Handwerk>> oder <<Hacken>> benötigen).

[.icon]#O# Du kannst Taschendiebstahl oder eine einfach Infiltration durchführen oder Deine Spuren in der
physischen Welt verwischen.

[.icon]#C# Du kannst Orte oder Personen ausspionieren, wenn Du physisch anwesend bist. Du kannst optisch
erkennbare Sicherheitsmaßnahmen wie Kameras, Sensoren usw. ausspionieren.

[.icon]#A# -

[.icon]#D# -

==== Empathie
Du kannst Empathie wie in den Fate Core Grundregeln beschrieben einsetzen.

Darüber hinaus wird Empathie auch für die Astraleben eingesetzt (siehe dazu <<Astrale Projektion>>).  

[.icon]#D# Zusätzlich zu den Verteidigungen aus den Fate Core Grundregeln kannst Du Dich gegen magische 
Angriffe auf der Astralebene verteidigen.

==== Fahren
Dient dem konventionellen Steuern von Fahrzeugen aller Art. Rigger können über das Extra _Riggen_
damit Fahrzeuge "by wire" steuern.

Du kannst mit dieser Fertigkeit auch Fahrzeuge rammen wenn Du einen Angriff durchführst. Weitere Details
sind in <<Rigger und Fahrzeuge>> zu finden.

==== Handwerk / Tech
Umfasst alle Arten von Arbeiten an Maschinen (Fahrzeuge, Drohnen, Computer, Schlösser, Waffen, ...). Du kannst
die Aktionen wie in den Fate Core Grundregeln beschrieben einsetzen.

Diese Fertigkeit erfordert eine zusätzliche Unterkategorie. Zu den Kategorien gehören bspw.

* Fahrzeuge (ggf. weiter unterteilt nach Autos, Luftfahrzeuge, Drohnen, ...)
* Elektronik (wie bspw. elektronische Schlösser, Kameras, Sensoren, ...)
* Computer (Hard- und Software)

Jede Unterkategorie wird als eigenständige Fertigkeit behandelt. Du kannst beliebig viele Unterkategorien
erwerben - auch auf unterschiedlichen Fertigkeitsstufen.

[.icon]#O# Du kannst Hindernisse wie mechanische Schlösser überwinden oder defekte Fahrzeuge reparieren. Du
kannst Computerprogramme schreiben, die ein Problem für Dich lösen (bspw. eine große Datenmenge zu filtern).

[.icon]#C# Du kannst die Fertigkeit einsetzen, um Vorteile durch die Modifikation von technischen Gegenständen
zu erziehlen, bspw. in dem Du ein Fahrzeug tunst oder eine Waffe modifizierst. Du kannst auch technische 
Geräte sabbotieren oder Computerprogramme schreiben, die eine Recherche vereinfachen.

[.icon]#A# -

[.icon]#D# -

==== Hacken
*Neue Fertigkeit*

NOTE: Kann nur erworben werden, wenn Du das Extra _Decker_ oder _Technomancer_ hast. Siehe <<Matrix>>.

Du kannst _Hacken_ einsetzen um in der Matrix Daten zu suchen, zu entschlüsseln oder Dich leise zu bewegen.
_Hacken_ wird auch für die Initiative im Matrixkampf genutzt.

[.icon]#O# Du kannst Daten auffinden, sie entschlüsseln. Du kannst versuchen, Verteidigungsmaßnahmen durch
"schleichen in der Matrix" zu umgehen.

[.icon]#C# Du kannst Aspekte erschaffen, die Dir im Matrixkampf einen Vorteil bieten, bspw. in dem Du 
Programme nutzt, die Deine digitale Signatur verschleiern. Du kannst Deine digitalen Spuren nach einem 
Einbruch in einen Host verwischen.

[.icon]#A# -

[.icon]#D# -

==== Heimlichkeit
_Heimlichkeit_ wird wie in den Fate Core Grundregeln beschrieben verwendet.

==== Kämpfen
_Kämpfen_ wird wie in den Fate Core Grundregeln für Nahkämpfe verwendet.

==== Kontakte
_Kontakte_ beschreibt Deine soziale Vernetzung und ersetzt die _Connections_ aus dem Shadowrununiversum.

[.icon]#O# Du kannst die Fertigkeit einsetzen, um Hindernisse durch Connections zu lösen, in dem Du den 
passenden Dealer für den Verkauf von heißer Ware findest oder einen Mechaniker, der Deine Karre wieder
repariert.

[.icon]#C# Du kannst Vorteile erschaffen, wie bspw. einen Bekannten, der Dir die richtigen Hintergrundinfos
beschafft oder einen Aussteiger aus der lokalen Gang, der Dir den Ort des Geheimverstecks erzählt.

[.icon]#A# -

[.icon]#D# Du kannst Dich gegen soziale Angriffe verteidigen, in dem Du Connections hast, die Deine Reputation
verbessern.

==== Kraft
_Kraft_ wird wie in den Fate Core Grundregeln beschrieben eingesetzt. Dies gilt auch für die Sonderregel,
die Dir zusätzlich Kästchen für körperlichen Stress verschafft.

==== Magie
*Neue Fertigkeit*

NOTE: Kann nur erworben werden, wenn Du das Extra _Magier_ hast. Siehe <<Magie>> für Details.

Wird für das Sprechen von Zaubern verwendet.


[.icon]#O# Du kannst mittels Magie ein Hindernis überwinden, bspw. eine verschlossene Tür öffnen.

[.icon]#C# Du kannst mittels Magie einen Vorteil erlangen, bspw. unsichtbar werden, größer wirken oder eine 
Ablenkung in Form eines heranstürmenden Critters erzeugen.

[.icon]#A# Du kannst Kampfzauber verwenden, um andere Charakter in der physischen Welt anzugreifen.

[.icon]#D# Du kannst Gegenzauber verwenden um Dich gegen magische Angriffe in der physischen Welt zu 
verteidigen.

==== Matrixkampf
*Neue Fertigkeit*

NOTE: Kann nur erworben werden, wenn Du das Extra _Decker_ oder _Technomancer_ hast. Siehe <<Matrix>>.

Mit der Fertigkeit _Matrixkampf_ kannst Du Konflikte in der Matrix ausfechten. 

[.icon]#O# -

[.icon]#C# -

[.icon]#A# Du kannst Programme starten, die gegnerische Programme bekämpfen und so Schaden verursachen.

[.icon]#D# Du kannst Programme starten oder Firewalls aktivieren, die Dich vor feindlichen Angriffen
schützen.

==== Nachforschungen
Mit dieser Fertigkeit kannst Du Recherchen in der Matrix (über einen konventionellen, legalen Zugang) starten
um Informationen über Orte, Personen, Konzerne, Ereignisse usw. ausfindig zu machen. Die Fertigkeit entspricht
der Beschreibung in den Fate Core Grundregeln.

==== Provozieren
Du kannst _Provozieren_ wie in den Fate Core Grundregeln beschrieben einsetzen.

Darüber hinaus wird die Fertigkeit auch für Angriff in der Astraleben eingesetzt; siehe dazu
<<Astrale Projektion>>.

[.icon]#A# Du kannst Angriffe in der astralen Projektion durchführen.

==== Ressourcen

NOTE: Kann nicht regulär erworben oder gesteigert werden. Siehe die Beschreibung unter <<Ressourcen>>.

Mit der Fertigkeit _Ressourcen_ kannst Du Dinge und Informationen kaufen, Leute bestechen und Du drückst
dadurch Deinen Lebensstil aus.

[.icon]#O# Du kannst Ressourcen nutzen, um Hindernisse, die sich Geld aus der Welt schaffen lassen zu 
überwinden. Dazu gehört insbesondere das Bestechen von Personen oder das Kaufen von Gegenständen und 
Informationen.

[.icon]#C# Du kannst Ressourcen nutzen, um Personen Aspekte hinzuzufügen, dass sie Dir freundlich gestimmt
sind, wenn sie für Geld anfällig sind. Du kannst auch einen Vorteil erschaffen, in dem Du einen Aspekt für
einen Ausrüstungsgegenstand hinzufügst, der eine finanzielle Aufwertung darstellt, bspw. ein RedDot-Visier
für ein Sturmgewehr.

==== Schießen
Du benutzt _Schießen_ um Deine Fernkampfwaffe einzusetzen. Überlicherweise tust Du dies beim _angreifen_, aber
Du kannst es auch sehr gut verwenden um einen _Vorteil zu erschaffen_ (z.B. [.aspekt]#Sperrfeuer# oder
[.aspekt]#Feuerschutz#). In einigen Fällen kannst Du damit auch ein _Hindernis überwinden_.

[.icon]#O# Schießen wird in der Regel nicht für das Überwinden genutzt. Du kannst es aber für 
Schießwettbewerbe nutzen oder aber auch um einen unbeweglichen Gegenstand wie eine Überwachungskamera zu
zerstören.

[.icon]#C# Du kannst mit Schießen in einem Konflikt verschiedene Vorteile erschaffen, wie bspw. 
[.aspekt]#Deckungsfeuer# oder [.aspekt]#festgenagelt#. Du kannst auch versuchen, deine Gegner zu 
[.aspekt]#entwaffnen#.

[.icon]#A# Natürlich kannst Du Schießen einsetzen, um mit einer Fernkampfwaffe anzugreifen.

[.icon]#D# -

==== Täuschung
Täuschung wird wie in den Fate Core Grundregeln beschrieben eingesetzt.

==== Wahrnehmung
Wahrnehmung wird wie in den Fate Core Grundregeln beschrieben eingesetzt, bezieht sich dabei aber immer nur 
auf die reale Welt.

==== Wille
Wille wird wie in den Fate Core Grundregeln beschrieben eingesetzt. Dies gilt insbesondere auch für die 
Sonderregel, die Dir zusätzliche Stressfelder für geistigen Stress bietet.

Darüber hinaus wird die Fertigkeit für Fortbewegung und Verteidigung in der astralen Projektion genutzt;
siehe dazu <<Astrale Projektion>>.

[.icon]#O# Du kannst Dich in einem Konflikt in der astralen Projektion zwischen Zonen fortbewegen und
andere Hindernisse überwinden, so wie Du es mittels <<Athletik>> in der realen Welt machst.

[.icon]#C# -

[.icon]#A# -

[.icon]#D# Du nutzt Wille für die Verteidigung gegen Angriffe während Du astral projizierst.

==== Wissen
In Bezug auf die Aktionen wird Wissen wie in den Fate Core Grundregeln beschrieben eingesetzt.

Wissen erfordert eine Spezialisierung, die bei der Fertigkeit angegeben werden kann.
Es können mehrere Spezialisierungen als unabhängige Fertigkeiten erworben werden. Beispiele für 
Spezialisierungen:

* Bioware
* Cyberware
* Computer
* Kriminelle Organisation, wie Mafia, Yakuza, usw.
* Konzerne
* Matrix
* Medizin
* Strassenwissen / Strassengangs

== Magie
In der erwachten Welt von Shadowrun existieren Metamenschen und Critter, die Magie einsetzen können.
Magie wird in _Schicksalhafte Schatten_ nach den Regeln für _Extras_ aus den Fate Core Grundregeln realisiert.

.Extra: Magie
****
*Voraussetzung*: Dein <<Konzept>> muss erwähnen, welcher Form der Magie (Magier, Hexenmeister, Schamane,
Adept) Du folgst.

*Preis*: Du musst mindestens 3 Fertigkeitsstufen in _Magie_ haben. Reduziere Deine Erholungsstufe um 1.

NOTE: Nur Charaktere mit diesem Extra dürfen Fertigkeitsstufen in _Magie_ besitzen und diese Fertigkeit 
einsetzen.

NOTE: Wenn Du Magie einsetzen möchtest _darfst_ Du keine <<Bio- und Cyberware>> 
verwenden.

Du kannst _Magie_ nach den unten beschriebenen Regeln einsetzen.
****

Magie und Bio- oder Cyberware vertragen sich nicht. Shadowrun verwendet die _Essenz_ um
das zu repräsentieren. Das gibt Magieanwendern die Möglichkeit eine kleine Menge an
Bio- oder Cyberware einzusetzen. _Schicksalhafte Schatten_ ist hier strikter: Erwachte Personen
können keine Bio- oder Cyberware einsetzen. Wenn ein erwachter Charakter im Verlauf der
Entwicklung Bio- oder Cyberware implantiert bekommt verliert er den Zugriff auf seine
Magie-Fähigkeiten.

=== Zauber sprechen
Das Sprechen eines Zaubers erfordert eine Probe auf _Magie_. Je nach Situation kann dies ein _Hindernis
überwinden_, einen _Vorteil erschaffen_ oder auch _Angreifen_ und _Verteidigen_ sein.

==== Entzug
Das Sprechen von Zaubern kostet viel Kraft, Anstrengung und Konzentration. Jeder Zauber verursacht 
geistigen Stress. Der Stress wird wie ein Angriff der Magie gegen Dich gewertet. SL: Du legst die 
Fertigkeitsstufe des Angriffs für den Zauber fest. Die Fertigkeitsstufe kann sich in Abhängigkeit des Zaubers 
(Art des Effekts) und der äußeren Umstände ändern. Ein und der selbe Zauber können unterschiedliche starke 
Angriffe hervorrufen. Du kannst _Wille_ einsetzen, um Dich gegen den Angriff zu verteidigen. 

Der Stress wird unabhängig davon verursacht, ob der Zauber erfolgreich war oder nicht.

==== Zauber aufrechterhalten
Jeder aufrechterhaltene Zauber (bspw. eine magische Rüstung oder Barriere) funktioniert wie ein freie Einsatz
für den "angreifenden Zauber" und erhöht den Entzug um +2. SL: Du muss diesen "freien Einsatz" berücksichtigen
wenn Du für den Zauber angreifst.

==== Stunts für Zauber
Charaktere können Stunts erwerben, um bestimmte Zauber (bspw. _Feuerball_ oder _Heilung_) mit einem
Bonus verwenden zu können. Diese können auch beinhalten, dass sie einen Bonus bei der Entzugsprobe bekommen.

=== Astral Wahrnehmen
Nutzer mit dem Extra _Magie_ können astral wahrnehmen. Dazu nutzen sie die Fertigkeit _Empathie_ um entweder
ein Hindernis zu überwinden oder einen Vorteil zu erschaffen.

=== Astrale Projektion
Charaktere mit dem Extra _Magie_ können den Stunt _Astrale Projektion_ erwerben und sich dann astral 
projizieren. Der physiche Körper wird dann bewusstlos und der Geist des Charakters befindet sich in der 
Astralebene. 

Die Astrale Projektion selber erfordert keinen Fertigkeitswurf. In der Astralebene werden alternative
Fertigkeiten genutzt.

Empathie:: wird anstelle von _Wahrnehmung_ sowohl für die Wahrnehmung als auch für die Initiative 
verwendet.
Wille:: wird anstelle von _Atheltik_ verwendet, wenn es um sportliche Fortbewegung geht. 
Ebenfalls wird _Wille_ verwendet, um sich im Astralkampf gegen Angriffe zu verteidigen.
Provozieren:: wird verwendet, um im Astralkampf einen Gegner anzugreifen.

== Matrix
Die Matrix ist das allumgebene Computernetzwerk in der Welt von Shadowrun und steuert so gut wie alle 
technischen Geräte. Charaktere können sich in die Matrix einloggen, dort nach Daten suchen, in andere 
Systeme einbrechen und in der Matrix kämpfen.

Es gibt verschiedene Arten die Matrix zu benutzen. Normale Nutzer greifen mittels ihres ComLink auf die
Matrix zu. Nutze die Fertigkeit _Nachforschungen_ um nach Informationen zu suchen.

Wer in fremde Systeme einbrechen will, muss etwas weiter gehen. Dafür gibt es zwei Arten: Charaktere können
sich mit einer Datenbuchse (Cyberware) und einem Cyberdeck in die Matrix einloggen oder sie nutzen
_Resonanz_ - eine besondere erwachte Fähigkeit, die die Nutzung der Matrix ohne technisches Equipment
ermöglicht.

[sidebar]
****
Sowohl Decker als auch Technomancer nutzen regeltechnisch die Fertigkeiten _Hacken_ und _Matrixkampf_. Dennoch
sollten sich die erzählerischen Details bei der Nutzung stark unterscheiden.
****

.Extra: Decker
****
*Voraussetzung*: Dein Charakterkonzept benennt Dich als "Decker".

*Preis*: Du musst mind. 2 Fertigkeitsstufen in _Hacken_ und mind. 2 Fertigkeitsstufen in _Matrixkampf_
investieren. Reduziere Deine Erholungsstufe um 1.

Du erhältst die Cyberware _Datenbuchse_, über die Du Dich mit Deinem Cyberdeck verbinden kannst und die
Matrix nutzen kannst.

Du nutzt die Fertigkeit _Hacken_ anstelle von _Wahrnehmung_ um Dinge in der Matrix zu sehen, für die 
Initiative im Matrixkampf, für Proben um Daten zu erlangen und anstelle von _Heimlichkeit_. Du nutzt die 
Fertigkeit _Matrixkampf_ für Angriff und Verteidigung in der Matrix.

Stress, den Du im Matrixkampf erleidest, wird gegen Deinen körperlichen Stress gerechnet.
****

.Extra: Technomancer
****
*Voraussetzung*: Dein Charakterkonzept benennt Duch als Technomancer.

*Preis*: Du musst mind. 2 Fertigkeitsstufen in _Hacken_ und mind. 2 Fertigkeitsstufen in _Matrixkampf_
investieren. Reduziere Deine Erholungsstufe um 1.

Du kannst die Matrix durch die besondere Fähigkeit der Resonanz nutzen.

Du nutzt die Fertigkeit _Hacken_ anstelle von _Wahrnehmung_ um Dinge in der Matrix zu sehen, für die 
Initiative im Matrixkampf, für Proben um Daten zu erlangen und anstelle von _Heimlichkeit_. Du nutzt die 
Fertigkeit _Matrixkampf_ für Angriff und Verteidigung in der Matrix.

Stress, den Du im Matrixkampf erleidest, wird gegen Deinen geistigen Stress gerechnet.
****

Computerprogramme, die Du einsetzen möchtest, werden über _Vorteile_ ausgedrückt. Computerprogramme, die ein
Host gegen Dich einsetzt können entweder über passiven Widerstand oder als Charakter eingesetzt werden.

== Rigger und Fahrzeuge

Rigger steuern Fahrzeuge über eine direkte Verbindung zwischen dem Fahrzeug und dem Gehirn. Dafür nutzen sie
eine spezielle Datenbuchse.

.Extra: Rigger
****
*Voraussetzung*: Dein Charakterkonzept benennt Dich als Rigger.

*Preis*: Du musst mind. 3 Fertigkeitsstufen in _Fahren_ investieren. Reduziere Deine Erholungsstufe um 1.

Du erhälst eine Riggerkontrolle (Cyberware), die auch als Datenbuchse fungiert. Darüber kannst Du geriggte
Fahrzeuge mental steuern.

Du kannst soviele Fahrzeuge und Drohnen parallel steuern, wie es Deiner Fertigkeitsstufe in _Fahren_ 
entspricht.
****

[sidebar]
****
Fahrzeuge nutzen die _bronzene Fate Regel_ ("Alles kann als Charakter dargestellt werden.") und werden wie
Charaktere behandelt. Das bedeutet:

* Fahrzeuge haben Aspekte
* Fahrzeuge haben Fertigkeiten
* Fahrzeuge haben Stunts

Fahrzeuge haben _keine_ Erholungsstufe; Fate Punkte muss der Fahrer einsetzen.
****

== Ressourcen

Ressourcen spielen eine wichtige Rolle in der Welt von Shadowrun. Damit die Spieler nicht jeden 
einzelnen Nuyen ihrer Charaktere buchhaltärisch erfassen müssen, verwendet _Schicksalhafte Schatten_ ein
einfacheres System basierend auf der Fertigkeit _Ressourcen_ aus den Grundregeln von Fate Core.

Abweichen zu den Grundregeln kann diese Fertigkeit jedoch nicht erworben werden und wird auch nicht
in der Fertigkeitenpyramide oder zur Säulenbildung mit herangezogen. Diese Fertigkeit wird durch die 
Spielleitung gesteuert und zu _Meilensteinen_ modifiziert. Dabei sind auch größere Sprünge möglich.

Die Spieler können diese Fertigkeit wie in den Grundregeln beschrieben einsetzen um kleinere 
Ausrüstungen zu kaufen, Connections zu bestechen usw.

====
Die Charaktere haben einen Run erfolgreich abgeschlossen - und wurden dafür sogar bezahlt. Die Spielleitung 
erhöht die Fertigkeit Ressourcen daher auf "Gut (+3)" um den finanziellen Wohlstand
auszudrücken. Einer der Charaktere kauf nun ein neues, kostspieliges Fahrzeug. Die Spielleitung 
reduziert die Fertigkeit für ihn auf "Durchschnittlich (+1)", da er einen Großteil des verdienten Geldes 
wieder ausgegeben hat.
====

== Waffen, Rüstungen und Munitionsverbrauch

Waffengefechte im Universum von Shadowrun sind tödlich und ein Ausweichen gegen ein 
Hochgeschwindigkeitsgeschoss ist selbst mit Reflexbooster nicht wirklich möglich. Daher kann gegen 
Fernkampfangriffe _keine_ Verteidigung eingesetzt werden.


[sidebar]
****
Waffen und Ausrüstungen folgen den Extras-Regeln aus dem Fate Core Grundregelbuch ab S.285. Sie 
verfügen über eine Waffen- bzw. Rüstungsstufe, die zusätzliche Erfolgsstufen generieren bzw.
egalisieren.
****

Waffen liefern zusätzliche Trefferstufen bei einem Erfolg, Rüstungen "verschlucken" Trefferstufen bei 
einem Treffer. Es gibt vier Stufen für Waffen und Rüstungen.

<<<

=== Waffen und Rüstungen

[frame=ends, grid=rows, stripes=even, cols="^1,3*<4a"]
|===
| Stufe | Fernkampfwaffen | Nahkampfwaffen | Rüstungen

| 0
| -
| 
* Faustkampf
* Ringkampf
| 
* nackte Haut
* Alltagskleidung

| 1
| 
* Holdout-Pistolen
* leichte Pistolen
* Automatikpistolen
* Shuriken
* Wurfmesser
| 
* Messer
* improvisierte Waffen (Motorradkette, Besenstiel, ...)
| 
* Panzerkleidung
* Chamäleonanzug

| 2
| 
* schwere Pistolen
* Maschinenpistolen
* Betäubungsgranaten
| 
* Schlagring
* Kampfmesser
* Knüppel
| 
* Panzerweste
* Panzerjacke
* Gefütterter Mantel

| 3
| 
* Schrotflinten
* Jagdgewehre
* Sturmgewehre
* Splittergranaten
* Sprenggranaten
| 
* Kampfaxt
* Katana
* Schwert
| 
* Ganzkörperpanzerung

| 4
| 
* Scharfschützengewehre
* Maschinengewehre
* Granaten- und Raketenwerfer
* Sprengstoffe
| 
| 
* militärische Spezialpanzerungen
|===

Andere Schutzausrüstungen wie Helme, Antiterrorschilde oder ähnliches werden nicht durch Rüstungsstufen
repräsentiert sondern sollten dem Charakter einen entsprechenden Aspekt verleihen, den er einsetzen kann.

=== Munitionsarten
Im Shadowrun-Universum gibt es unterschiedliche Munitionsarten wie Explosiv oder APDS. Diese haben 
unterschiedliche Vor- und Nachteile und modifizieren den Schaden der Waffe, mit der sie verschossen werden.
In _Schicksalhafte Schatten_ werden diese Munitionsarten nicht unterschieden. Wenn Euch das für Euer Spiel
wichtig ist könnt Ihr Aspekte verwenden wie bspw. [.aspekt]#APDS-Munition#, die Dir freie Einsätze beschert,
die bspw. die Waffenstufe um +1 verbessern oder Panzerung ignorieren.

=== Munitionsverbrauch
In Shadowrun wird die Munition sehr genau gezählt und die Charaktere können sehr schnell in die Situation 
kommen, dass sie keine Munition mehr haben. In _Schicksalhafte Schatten_ wird Munition anders gezählt. 

Wenn Du bei einer _Schießen_ Probe (egal ob Angriff oder Vorteil) einen Gleichstand erziehlst bekommst Du 
als kleinen Haken den Aspekt [.aspekt]#Magazin leer#. Mit diesem Aspekt kannst Du nicht mehr weiter schießen. 
Du musst erst nachladen. 

==== Nachladen
Nachladen im Feuergefecht ist nicht immer ganz einfach. Du musst dazu ein Hindernis überwinden und kannst 
dafür _Schießen_ oder _Handwerk_ verwenden. Der passive Widerstand ist ordentlich (+2). Bei einem Erfolg 
kannst Du die Aspekte [.aspekt]#Magazin leer# und [.aspekt]#wenig Muni# (siehe <<Automatikmodus>>) entfernen.

==== Automatikmodus
Waffen im Shadowrun-Universum verfügen über verschiedene Feuermodi wie Einzelschuss, Halb-Automatik, Salven
und Automatikfeuer. _Schicksalhafte Schatten_ modelliert diese nicht. Das Waffen- und Schadenssystem macht 
Schusswaffen zu einer tödliche Bedrohung und dies berücksichtigt schon einen Großteil der unterschiedlichen
Feuermodi. 

Eine Ausnahme zu dieser Regel ist der _Automatikmodus_. Alle Shadowrun-Waffen mit dem Feuermodus _AM_ können
im Automatikmodus feuern. Automatikmodus erlaubt Dir, mehrere Ziele innerhalb einer Zone zu verletzen. Dazu
würfelst Du den normalen Angriff und kannst anschließend die Erfolgsstufen auf unterschiedliche Gegner 
verteilen. Diese müssen sich in der selben Zone aufhalten und es sollte plausibel sein, dass Du sie mit einem
Feuerstoß erreichen kannst.

Nachdem Du Deine Waffe im Automatikmodus abgefeuert hast bekommst Du den Aspekt [.aspekt]#wenig Muni#. Dieser
Aspekt kann von Dir nicht genutzt werden, aber auch nicht von Gegnern. Wenn Du diesen Aspekt ein zweites Mal
bekommen würdest, wird er entfernt und Du bekommst statt dessen den Aspekt [.aspekt]#Magazin leer# wie oben
beschriebebn. Du kannst [.aspekt]#wenig Muni# durch _Nachladen_ entfernen.

====
Du schießt mit einer Uzi auf eine Gruppe von Schreckhähne. In Deiner Zone befinden sich vier Schreckhähne.
Du würfelst ein gutes (+3) Ergebnis. Die Uzi hat Waffenstufe 2 so dass Du auf 5 Erfolgsstufen kommst.
Du kannst diese 5 Stufen nun auf 4 Gegener verteilen. Du könntest einem Schreckhahn 3 Erfogsstufen und einem
weiteren 2 Erfeolgsstufen zuordnen. Du könntest auch drei Hähnen jeweils 1 Erfolgsstufe und einem Hahn 2
Stufen geben.
====

=== Reichweiten

Es gibt keine pauschalen Reichweitenbegrenzungen für Waffen. Statt dessen solltet ihr gemeinsam überlegen,
welche Gegner von einer Waffe noch erreicht werden können. Verwendet Aspekte wie [.aspekt]#sehr weit 
entfernt# mit freien Einsätzen für die Verteidigung um entsprechende Situationen aufzulösen.

=== Granaten und Sprengstoffe

Granaten und Sprengstoffe richten Schaden an, der in der Regel mehrere Personen betrifft. Granaten 
betreffen grundsätzlich _alle Personen innerhalb einer Zone_ (egal ob Freund oder Feind) und richten
bei allen den entsprechenden Schaden an. 

Sprengstoffe verhalten sich ähnlich, können aber je nach Menge und Einsatz mehr als eine Zone betreffen.

== Bio- und Cyberware

Bio- und Cyberware verbessern oder erweitern die metamenschlichen Fähigkeiten, so dass Nutzer dieser
"Einbaugeräte" vielen Normalsterblichen überlegen sind. Der Preis dafür ist, dass die Geräte einen 
gewissen Teil der Metamenschlichkeit rauben.

[sidebar]
****
Bio- und Cyberware werden über _Stunts_ aus den Fate Core Grundregeln realisiert. Jede Bio- bzw.
Cyberwaremodifikation muss als _Stunt_ erworben werden.
****

=== Adrenalinpumpe
Ein Adrenalinschub steigert kurzfristig deine körperliche Leistungsfähigkeit. Du kannst die Adrenalinpumpe 
jederzweit auslösen - in Konflikten aber nur, wenn Du an der Reihe bist. Du erhälst den Aspekt 
[.aspekt]#aufgeputscht# mit zwei freien Einsätzen (so als hättest Du einen Vorteil mit einem vollen Erfolg 
erziehlt). Nach dem Ende des Konflikts oder er Anstrengung (bspw. einem Wettstreit oder einer Herausforderung) 
verlierst Du den Aspekt [.aspekt]#aufgeputscht# (noch offene freie Einsätze verfallen) und Du bekommst den 
Aspekt [.aspekt]#erschöpft#, den die SL gegen Dich einsetzen darf. Du kannst den Aspekt durch ausruhen 
ablegen. 

=== Dermalpanzerung
Unter der Haut implantierte Platten bieten Dir zusätzlichen Schutz gegen körperlichen Schaden. Die 
Dermalpanzerung gilt als Rüstung der Stufe 1, die kumulativ zu darüber getragenen Rüstungen ist.

Du bekommst den Aspekt [.aspekt]#beinahe künstliche Haut#, die die SL gegen Dich einsetzen kann.

=== Cyberarm
Du hast einen künstlichen Arm, der über eine gesteigerte Kraft verfügt. Für alle Proben, die Du mit diesem
Arm durchführst, bekommst Du +2 auf den Fertigkeitswurf.

Der Arm stellt den Aspekt [.aspekt]#Cyberarm# dar, der gegen Dich eingesetzt werden kann.

=== Cyberaugen
Du hast künstliche Augen, die über verbesserte optische Fähigkeiten verfügen, darunter Restlichtverstärkung,
Infrarotsicht, optischer Zoom und eine Blitzkompensation. Du kannst diese Fähigkeiten mental steuern. Die 
Augen sind als solche erkennbar, wenn jemand Deine Augen direkt sehen kann.

Bei Proben auf _Wahrnehmung_ oder _Nachforschungen_, die optischer Natur sind, kannst Du +2 auf Deinen Wurf
addieren.

=== Kommlink
Du hast ein implantierten Kommlink, der alle Funktionen des "klassischen" Kommlinks entspricht und darüber
hinaus mit eine Sim-Modul ausgestattet ist.

=== Reflexbooster I
Bei der Bestimmung Deiner Initiative in körperlichen Konflikten bekommst Du +2 auf die _Wahrnehmung_. 

=== Reflexbooster II
NOTE: Du musst <<Reflexbooster I>> haben um diese Cyberware verwenden zu können.

Nachdem ein Austausch in einem Konflikt abgehandelt wurde, bekommen alle Charaktere mit einem Reflexbooster II
eine weitere Handlungsmöglichkeit, in der sie eine weitere Handlung durchführen können. Die Reihenfolge dieser
Handlungen nutzt die selbe Initiativreihenfolge. Anschließend folgt der nächste Austausch.

Das Aktivieren des Reflexboosters erfordert eine Handlung innerhalb eines Austausch (Du musst dafür aber nicht
würfeln). Das gleiche gilt für das Deaktivieren.

=== Smartlinkverbindung I
Über eine implantierte Kontaktstelle in der Hand kannst Du Daten mit einer Smartgun austauschen. Du musst über
<<Cyberaugen>> verfügen, die Dir dann eine Zielmarkierung anzeigen. Du bekommst einen Bonus von +2 auf alle
Versuche mit <<Schießen>> einen Vorteil zu erschaffen (also Zielen, Sperrfeuer, usw.). 

=== Smartlinkverbindung II
NOTE: Du musst <<Smartlinkverbindung I>> haben, um diese Cyberware verwenden zu können. 

Du bekommst zusätzlich einen Bonus von +2 auf alle Proben, wenn Du mit _Schießen_ angreifst.

=== Talentbuchse
Du hast eine implantierte Buchse, in die Du _Talentsofts_ einsetzen kannst. Über die Talensofts kannst Du die
darauf gespeicherten Fertigkeiten so nutzen, als hättest Du die Fertigkeit gewählt. Die Fertigkeitsstufe ist
in der Regel _ordentlich (+2)_, aber es gibt auch Talentsofts mit anderen Fertigkeitsstufen.

=== Talentleitung
NOTE: Du musst eine <<Talentbuchse>> haben, damit Du die Talentleitung erwerben kannst.

Mit der Talentleitung kannst Du auch Aktionsfertigkeiten über _Talentsofts_ nutzen. Dies gilt _nicht_ für
Fertigkeiten, die Du sonst nur über Extras erwerben kannst, wie <<Magie>>, <<Hacken>>, <<Matrixkampf>>,
<<Ressourcen>>.

== Weitere Ausrüstung

Für viele Runner gilt: "Du bist was Du hast!". Fate Core verwendet hier einen anderen
Ansatz: Es wird davon ausgegangen, dass die Charaktere die notwendige Ausrüstung haben,
die sie für ihre Fertigkeiten benötigen. Diese Regel soll uneingeschränkt gelten. Es gibt
in _Schicksalhafte Schatten_ keine Einwegspritzen, kein Brecheisen, keine Dietriche oder 
ähnliches. Statt dessen wird davon ausgegangen, dass die Charaktere dies einfach haben.

SL: Du kannst einen Vorteil erschaffen lassen, der die Ausrüstung repräsentiert.

Dennoch gibt es einige besondere Ausrüstungen, die gesondert aufgeführt werden.

=== DocWagon-Vertrag
DocWagon ist der größte weltweit operierende Dienstleister für die Notfallversorgung.
Mit einem DocWagon-Vertrag kannst Du Dir diese Dienst sichern, wenn Du sie brauchst.
Es gibt den Vertrag in verschiedenen Stufen: Standard, Gold, Platin, Superplatin. Je
Stufe werden unterschiedliche Kosten fällig.

In _Schicksalhafte Schatten_ haben alle Charaktere einen DocWagon-Vertrag - außer sie wollen dies explizit 
_nicht_. Die Verträge haben _keine_ Vertragsstufen - statt dessen werden Kosten bei der Inanspruchnahme 
abhängig von den Leistungen fällig. Bei der Nutzung des Vertrags musst Du mittels _Ressourcen_ ein Hindernis 
überwinden. Der Schwierigkeitsgrad richtet sich nach den gewünschten Leistungen und sollte zwischen +1 und +5 
liegen.

[appendix]
include::./changelog.adoc[leveloffset=1]

== Lizenz

Die Regeln von _Schicksalhafte Schatten_ werden unter der 
http://www.opengamingfoundation.org/ogl.html[Open Gaming License (OGL) Version 1.0a] veröffentlicht. Diese
Arbeit basiert auf den Regeln von Fate Core, die ebenfalls unter der OGL veröffentlicht werden.

The Fate Core font is © Evil Hat Productions, LLC and is used with permission. The Four Actions icons were 
designed by Jeremy Keller.